### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by PureFox48** [CrazyInfin8/WrenGo#1]
Firstly, thanks for creating this which is a useful adjunct for those of us who like to program in Go :)

Just three minor issues I've encountered so far.

Firstly, when I'm using Wren-cli, if I import a library module like this:

```javascript
import "/someModule" for SomeClass

```
then Wren-cli would look for the file "./someModule.wren" and find it because I always copy such modules to the same directory as the startup script.

However, that's not happening with WrenGo. Either I have to use the library's full name (which is awkward if that in turn imports other modules) or I need to change the configuration like so:

```go
cfg := wren.NewConfig()
cfg.LoadModuleFn = func(vm *wren.VM, name string) (string, bool) {
    if !strings.HasPrefix(name, ".") {
        name = "." + name
    }
    if !strings.HasSuffix(name, ".wren") {
        name += ".wren"
    }
    return wren.DefaultModuleLoader(vm, name)
}
vm := cfg.NewVM()
```

Although this is not a big problem, it would be nice if the DefaultModuleLoader function could do it for us.

Secondly, I've noticed that when I set up a Go function to represent a static foreign method in Wren, 'parameters' includes an extra parameter (the first one) which is a *wren.Handle and is possibly a meta-class reference or similar. This had me puzzled for a while and it would be useful if there could be a mention in the docs about the extra parameter being passed.

Finally, I couldn't figure out how to wire up a foreign property in Wren i.e. one with no following parentheses. Again no big problem as I can always add the parentheses but if there is a way to do it perhaps you could elucidate.

**Comment by CrazyInfin8** [comment]
Ok sorry for not responding to this sooner.

For the first issue, I guess I find this more of a matter of personal preference. I think I like having module names without a precededing directory or a ".wren" to refer to built-in modules (that would be bundled into the executable) while actual paths can load external files.

There was a problem with your solution (at least while using WrenGo at the time this issue was probably opened).
```js
import "/someModule" for SomeClass
import "./someModule" for SomeClass
import "/someModule.wren" for SomeClass
import "./someModule.wren" for SomeClass
```
Since each of these import module names are all different, they would all be treated differently and each class would not match. To solve this I added functionality for the `WrenResolveModuleFn` function just now which allows you to modify the module name before it is passed to `LoadModuleFn`. I decided not to create a `DefaultModuleResolver` though because I still don't think it will work as nice as I want it to, at least without importing more librarys from go like "strings" or "filepath". 

As for the other two issues, I finally added a more comprehensive example to the `README.md` on how to do more complex stuff with foreign functions.
